### ISSUE TITLE
Add CI to run tests on every push and pull request on main branch

### ISSUE THREAD

**Issue by ghoshbishakh** [Pinggy-io/normalize-email#1]

**Comment by VedantPinggy** [comment]
To test and run github workflows locally:- [https://www.browserstack.com/guide/test-github-actions-locally#:~:text=To%20test%20GitHub%20Actions%20locally%2C%20you%20can%20use%20the%20GitHub,and%20validate%20our%20workflows%20locally.](url)

**Comment by VedantPinggy** [comment]
Done
